### PR TITLE
Issue #21: Upgrade to Ionic 2 beta 10

### LINKED ISSUE #21: Upgrade to Ionic 2 beta 10
Upgrade from Ionic 2 beta 8 to Ionic 2 beta 10, which fixes many bugs and changes the behavior of `ion-content`.

http://blog.ionic.io/ionic-2-beta-10-is-live/

https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-beta-10

https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#200-beta10-2016-06-27

### PR DESCRIPTION
**Pull request by mckoon**
Issue #21: Upgrade to Ionic 2 beta 10

Upgrades to Ionic 2 beta 10.
Cloned new cutepuppy project, then ported dose amigos into it.

Wraps ion-navbar with ion-header tags.
Removes *navbar attribute from ion-navbar.

Closes #21.

### CODE REVIEW

**Comment by mckoon** [comment]
Before merging this, I would like confirmation that it works for everyone.

1. Check out the PR on your workstation (look like instructions here: https://help.github.com/articles/checking-out-pull-requests-locally/#modifying-an-inactive-pull-request-locally)
2. Run `npm update` to get all the new versions of stuff installed.
3. Run `npm i`.
4. Run `ionic info` and confirm that the version of Ionic Framework is 2.0.0-beta.10.
5. Run `ionic serve` or `ionic serve --lab` and confirm it works.
6. Run `npm test` and confirm the karma tests run and pass.

**Comment by jking31cs** [comment]
I can't run ```npm i```.  I get the following error:

    npm WARN package.json doseamigos@ No repository field.
    npm WARN package.json doseamigos@ No license field.

    > doseamigos@ postinstall /Users/jking31cs/git-work/dose-amigos-ionic
    > typings install && cp test/karma-static/*.html node_modules/karma/static

    sh: typings: command not found

    npm ERR! Darwin 15.5.0
    npm ERR! argv "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/bin/npm" "i"
    npm ERR! node v4.1.1
    npm ERR! npm  v2.14.4
    npm ERR! file sh
    npm ERR! code ELIFECYCLE
    npm ERR! errno ENOENT
    npm ERR! syscall spawn
    npm ERR! doseamigos@ postinstall: `typings install && cp test/karma-static/*.html node_modules/karma/static`
    npm ERR! spawn ENOENT
    npm ERR!
    npm ERR! Failed at the doseamigos@ postinstall script 'typings install && cp test/karma-static/*.html node_modules/karma/static'.
    npm ERR! This is most likely a problem with the doseamigos package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     typings install && cp test/karma-static/*.html node_modules/karma/static
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls doseamigos
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/jking31cs/git-work/dose-amigos-ionic/npm-debug.log

However, nam test passes and ionic serve --lab works as intended and my ionic info shows the proper version.

**Comment by jking31cs** [comment]
👍

**Comment by geoffreygraddy** [comment]
I got the following errors running "npm i" and "npm install typings -g":

```
lawn-128-61-31-205:dose-amigos-ionic

 geoffreygraddy$ npm i

doseamigos@

 postinstall /Users/geoffreygraddy/Hive/School/Summer 2016/dose-amigos-ionic
typings install && cp test/karma-static/*.html node_modules/karma/static

sh: typings: command not found

npm WARN doseamigos@ No repository field.
npm WARN doseamigos@ No license field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v6.2.2

npm

 ERR! npm  v3.9.5
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! doseamigos@ postinstall: `typings install && cp test/karma-static/*.html node_modules/karma/static`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the doseamigos@ postinstall script 'typings install && cp test/karma-static/*.html node_modules/karma/static'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the doseamigos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && cp test/karma-static/*.html node_modules/karma/static
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs doseamigos
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls doseamigos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/geoffreygraddy/Hive/School/Summer 2016/dose-amigos-ionic/npm-debug.log
lawn-128-61-31-205:dose-amigos-ionic geoffreygraddy$ npm install typings -g
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
/usr/local/lib
└─┬ typings@1.3.1 
  ├── any-promise@1.3.0 
  ├── archy@1.0.0 
  ├── bluebird@3.4.1 
  ├─┬ chalk@1.1.3 
  │ ├── ansi-styles@2.2.1 
  │ ├── escape-string-regexp@1.0.5 
  │ ├─┬ has-ansi@2.0.0 
  │ │ └── ansi-regex@2.0.0 
  │ ├── strip-ansi@3.0.1 
  │ └── supports-color@2.0.0 
  ├─┬ columnify@1.5.4 
  │ └─┬ wcwidth@1.0.1 
  │   └─┬ defaults@1.0.3 
  │     └── clone@1.0.2 
  ├── listify@1.0.0 
  ├── minimist@1.2.0 
  ├─┬ typings-core@1.3.0 
  │ ├── array-uniq@1.0.3 
  │ ├─┬ configstore@2.0.0 
  │ │ ├─┬ dot-prop@2.4.0 
  │ │ │ └── is-obj@1.0.1 
  │ │ ├── object-assign@4.1.0 
  │ │ ├── os-tmpdir@1.0.1 
  │ │ ├── osenv@0.1.3 
  │ │ ├── uuid@2.0.2 
  │ │ └─┬ write-file-atomic@1.1.4 
  │ │   ├── imurmurhash@0.1.4 
  │ │   └── slide@1.1.6 
  │ ├─┬ debug@2.2.0 
  │ │ └── ms@0.7.1 
  │ ├─┬ detect-indent@4.0.0 
  │ │ └─┬ repeating@2.0.1 
  │ │   └─┬ is-finite@1.0.1 
  │ │     └── number-is-nan@1.0.0 
  │ ├── graceful-fs@4.1.4 
  │ ├─┬ has@1.0.1 
  │ │ └── function-bind@1.1.0 
  │ ├─┬ invariant@2.2.1 
  │ │ └─┬ loose-envify@1.2.0 
  │ │   └── js-tokens@1.0.3 
  │ ├─┬ is-absolute@0.2.5 
  │ │ ├─┬ is-relative@0.2.1 
  │ │ │ └─┬ is-unc-path@0.1.1 
  │ │ │   └── unc-path-regex@0.1.2 
  │ │ └── is-windows@0.1.1 
  │ ├── lockfile@1.0.1 
  │ ├─┬ make-error-cause@1.1.1 
  │ │ └── make-error@1.1.1 
  │ ├─┬ mkdirp@0.5.1 
  │ │ └── minimist@0.0.8 
  │ ├─┬ object.pick@1.1.2 
  │ │ └─┬ isobject@2.1.0 
  │ │   └── isarray@1.0.0 
  │ ├─┬ parse-json@2.2.0 
  │ │ └─┬ error-ex@1.3.0 
  │ │   └── is-arrayish@0.2.1 
  │ ├─┬ popsicle@6.2.1 
  │ │ ├── arrify@1.0.1 
  │ │ ├─┬ concat-stream@1.5.1 
  │ │ │ ├── inherits@2.0.1 
  │ │ │ ├─┬ readable-stream@2.0.6 
  │ │ │ │ ├── core-util-is@1.0.2 
  │ │ │ │ ├── process-nextick-args@1.0.7 
  │ │ │ │ ├── string_decoder@0.10.31 
  │ │ │ │ └── util-deprecate@1.0.2 
  │ │ │ └── typedarray@0.0.6 
  │ │ ├─┬ form-data@0.2.0 
  │ │ │ ├── async@0.9.2 
  │ │ │ ├─┬ combined-stream@0.0.7 
  │ │ │ │ └── delayed-stream@0.0.5 
  │ │ │ └─┬ mime-types@2.0.14 
  │ │ │   └── mime-db@1.12.0 
  │ │ ├── throwback@1.1.1 
  │ │ └── tough-cookie@2.2.2 
  │ ├─┬ popsicle-proxy-agent@2.0.2 
  │ │ ├─┬ http-proxy-agent@1.0.0 
  │ │ │ ├── agent-base@2.0.1 
  │ │ │ └── extend@3.0.0 
  │ │ └── https-proxy-agent@1.0.0 
  │ ├── popsicle-retry@3.2.1 
  │ ├── popsicle-status@2.0.0 
  │ ├── promise-finally@2.2.1 
  │ ├─┬ rc@1.1.6 
  │ │ ├── deep-extend@0.4.1 
  │ │ ├── ini@1.3.4 
  │ │ └── strip-json-comments@1.0.4 
  │ ├─┬ rimraf@2.5.3 
  │ │ └─┬ glob@7.0.5 
  │ │   ├── fs.realpath@1.0.0 
  │ │   ├─┬ inflight@1.0.5 
  │ │   │ └── wrappy@1.0.2 
  │ │   ├─┬ minimatch@3.0.2 
  │ │   │ └─┬ brace-expansion@1.1.5 
  │ │   │   ├── balanced-match@0.4.1 
  │ │   │   └── concat-map@0.0.1 
  │ │   ├── once@1.3.3 
  │ │   └── path-is-absolute@1.0.0 
  │ ├─┬ sort-keys@1.1.2 
  │ │ └── is-plain-obj@1.1.0 
  │ ├── string-template@1.0.0 
  │ ├─┬ strip-bom@2.0.0 
  │ │ └── is-utf8@0.2.1 
  │ ├── thenify@3.2.0 
  │ ├── throat@3.0.0 
  │ ├─┬ touch@1.0.0 
  │ │ └─┬ nopt@1.0.10 
  │ │   └── abbrev@1.0.9 
  │ ├── typescript@1.8.7 
  │ └── zip-object@0.1.0 
  ├─┬ update-notifier@1.0.2 
  │ ├─┬ boxen@0.6.0 
  │ │ ├── ansi-align@1.1.0 
  │ │ ├── camelcase@2.1.1 
  │ │ ├── cli-boxes@1.0.0 
  │ │ ├── filled-array@1.1.0 
  │ │ ├─┬ string-width@1.0.1 
  │ │ │ ├── code-point-at@1.0.0 
  │ │ │ └── is-fullwidth-code-point@1.0.0 
  │ │ └── widest-line@1.0.0 
  │ ├── is-npm@1.0.0 
  │ ├─┬ latest-version@2.0.0 
  │ │ └─┬ package-json@2.3.3 
  │ │   ├─┬ got@5.6.0 
  │ │   │ ├─┬ create-error-class@3.0.2 
  │ │   │ │ └── capture-stack-trace@1.0.0 
  │ │   │ ├── duplexer2@0.1.4 
  │ │   │ ├── is-redirect@1.0.0 
  │ │   │ ├── is-retry-allowed@1.1.0 
  │ │   │ ├── is-stream@1.1.0 
  │ │   │ ├── lowercase-keys@1.0.0 
  │ │   │ ├── node-status-codes@1.0.0 
  │ │   │ ├─┬ pinkie-promise@2.0.1 
  │ │   │ │ └── pinkie@2.0.4 
  │ │   │ ├── read-all-stream@3.1.0 
  │ │   │ ├── timed-out@2.0.0 
  │ │   │ ├── unzip-response@1.0.0 
  │ │   │ └─┬ url-parse-lax@1.0.0 
  │ │   │   └── prepend-http@1.0.4 
  │ │   ├── registry-url@3.1.0 
  │ │   └── semver@5.2.0 
  │ ├── lazy-req@1.1.0 
  │ ├─┬ semver-diff@2.1.0 
  │ │ └── semver@5.0.3 
  │ └─┬ xdg-basedir@2.0.0 
  │   └── os-homedir@1.0.1 
  ├── wordwrap@1.0.0 
  └── xtend@4.0.1 

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "typings" "-g"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/geoffreygraddy/Hive/School/Summer 2016/dose-amigos-ionic/npm-debug.log
```

**Comment by jking31cs** [comment]
@geoffreygraddy run `npm install typings -g`

**Comment by jleopold28** [comment]
👍

**Comment by geoffreygraddy** [comment]
👍

**Comment by mckoon** [comment]
Merging.

**Pull request merged**
